language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
  allow_failures:
    - rust: nightly

install:
    - cargo build --release --features "db_rocksdb, db_sled"

script:
    - cargo test --release --features "db_rocksdb, db_sled"
